default: &default
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: wbm
  password: wbm
  database: wbm
  encoding: utf8mb4
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 4 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
